package hlieb.model.weapons;

public enum WeaponAccessoriesType {
	SCOPE, HOLO_SCOPE, RAILCOVER, FRONT_GRIP, GRIP, SLING_MOUNT, BUTT, FORE_END, SLING, FLASHLIGHT, BIPOD, MAGHOLDER, LASER, MAG_PUL, SILENCER, NIGHT_SCOPE;
}
